name: medal
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pyyaml
  - ipykernel
  - jupyterlab
  - umap-learn

  # PyTorch + CUDA (no pip wheels)
  - pytorch
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio

  # Ray is fine via pip (conda builds sometimes lag)
  - pip:
      - ray==2.47.1
      - tensorboardx
      - pip-tools
      - pipreqs
      - umap-learn==0.5.7
