name: medal
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - tqdm
  - pyyaml
  - ipykernel
  - umap-learn

  # PyTorch + CUDA (no pip wheels)
  - pytorch
  - torchvision
  - torchaudio
  - opentsne
  - pyarrow
  - cmake

  # Ray is fine via pip (conda builds sometimes lag)
  - pip:
      - ray[tune]
      - tensorboardx
      - pip-tools
      - pipreqs
